
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wordpress-namespace
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
